### ISSUE TITLE
build fails when compiling ejabberd-15.06

### ISSUE THREAD

**Issue by p5n** [processone/p1_sip#4]
dict() type is undefined

Steps to reproduce:
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-all
make debug=true
...
==> esip (compile)
ejabberd-15.06/deps/esip/src/esip_listener.erl:40: type dict() undefined

Environment:
- current ArchLinux x86_64
- erlang 18.0-1
- rebar 1:2.6.0-1

**Comment by zinid** [comment]
Fixed
